# Generated by Django 4.0.6 on 2023-02-23 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_detail_dbo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='addtype',
            new_name='occupation',
        ),
    ]
