# Generated by Django 4.0.6 on 2023-02-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_detail2_eidn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=20)),
                ('rdob', models.DateField()),
                ('remail', models.EmailField(max_length=254)),
                ('rmobno', models.CharField(max_length=10)),
                ('rge', models.CharField(max_length=10)),
                ('rage', models.IntegerField()),
                ('rbg', models.CharField(max_length=10)),
                ('raddress', models.CharField(max_length=30)),
                ('roccupation', models.CharField(max_length=10)),
                ('rweight', models.IntegerField()),
                ('rheight', models.IntegerField()),
                ('ran', models.CharField(max_length=10)),
                ('rtmr', models.CharField(max_length=10)),
                ('rldd', models.DateField()),
                ('rdbo', models.CharField(max_length=10)),
                ('rimage', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
