# Generated by Django 4.0.6 on 2023-03-01 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('ofname', models.CharField(max_length=20)),
                ('oemail', models.EmailField(max_length=254)),
                ('omobno', models.IntegerField()),
                ('oaddress', models.CharField(max_length=30)),
                ('oimage', models.ImageField(upload_to='pictures')),
            ],
        ),
        migrations.AlterField(
            model_name='detail',
            name='mobno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='rdetail',
            name='rmobno',
            field=models.IntegerField(),
        ),
    ]
