# Generated by Django 4.0.6 on 2023-03-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_hdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('qfname', models.CharField(max_length=20)),
                ('qdob', models.DateField()),
                ('qemail', models.EmailField(max_length=254)),
                ('qmobno', models.IntegerField()),
                ('qge', models.CharField(max_length=10)),
                ('qage', models.IntegerField()),
                ('qbg', models.CharField(max_length=10)),
                ('qaddress', models.CharField(max_length=30)),
                ('qweight', models.IntegerField()),
                ('qheight', models.IntegerField()),
                ('qan', models.CharField(max_length=10)),
                ('qtmr', models.CharField(max_length=10)),
                ('qidtype', models.CharField(max_length=10)),
                ('qimage', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
