# Generated by Django 4.0.6 on 2023-03-10 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_quick_qaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupp',
            name='confirmpassword',
        ),
    ]
