# Generated by Django 4.0.6 on 2023-04-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rdetail2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('don_edit_email', models.EmailField(max_length=254)),
                ('don_edit_mobno', models.IntegerField()),
                ('don_edit_address', models.CharField(max_length=30)),
                ('don_edit_occupation', models.CharField(max_length=10)),
                ('don_edit_weight', models.IntegerField()),
                ('don_edit_height', models.IntegerField()),
                ('don_edit_an', models.CharField(max_length=10)),
                ('don_edit_tmr', models.CharField(max_length=10)),
                ('don_edit_ldd', models.DateField()),
                ('don_edit_sid', models.CharField(max_length=10)),
                ('don_edit_eidn', models.CharField(max_length=10)),
                ('don_edit_dsbg', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
