# Generated by Django 4.0.6 on 2023-04-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odetail2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('olicenceid', models.CharField(max_length=20)),
                ('oiimage', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
