# Generated by Django 4.0.6 on 2023-04-23 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_hdetail2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hdetail2',
            old_name='oiimage',
            new_name='hiimage',
        ),
        migrations.RenameField(
            model_name='hdetail2',
            old_name='olicenceid',
            new_name='hlicenceid',
        ),
    ]
