# Generated by Django 4.0.6 on 2023-02-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_signupp_delete_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='signupp',
            name='role',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
