# Generated by Django 4.0.6 on 2023-02-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_signupp_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('fullname', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('mobno', models.CharField(max_length=10)),
                ('ge', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('bg', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('addtype', models.CharField(max_length=10)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('an', models.CharField(max_length=10)),
                ('tmr', models.CharField(max_length=10)),
                ('ldd', models.DateField()),
                ('dbo', models.DateField()),
                ('image', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
