# Generated by Django 4.0.6 on 2023-02-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='dbo',
            field=models.CharField(max_length=10),
        ),
    ]
