# Generated by Django 4.0.6 on 2023-02-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_addtype_detail_occupation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('sid', models.CharField(max_length=10)),
                ('eidn', models.CharField(max_length=10)),
                ('dsbg', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
