# Generated by Django 4.0.6 on 2023-02-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_detail2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail2',
            name='eidn',
            field=models.IntegerField(),
        ),
    ]
