# Generated by Django 4.0.6 on 2023-04-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_rldd_rdetail_rlrd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rdetail2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('rsid', models.CharField(max_length=10)),
                ('reidn', models.IntegerField()),
                ('rdsbg', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
